title: streams-sizing
description: Constraint-based sizing tool for Red Hat Streams for Apache Kafka on OpenShift or RHEL (KRaft).
baseurl: "/streams-sizing"
url: "https://maximilianopizarro.github.io"

markdown: kramdown

exclude:
  - fixtures
